## How to run minibinder + scFv design fully end-to-end, locally.

This is a local-GPU adaptation of Biohub's [original tutorial](https://github.com/biohub/esm/tree/main/cookbook/tutorials), which uses Modal to parallelize design jobs on cloud GPUs. This version runs `binder_design.py`'s design loop directly on this machine's GPU instead — no Modal account or spend required, at the cost of running jobs sequentially instead of in parallel.

Biohub used this approach to design minibinders and scFvs against five therapeutically relevant targets — PDGFRB, EGFR, PD-L1, CD45, and CTLA4 — spanning receptor tyrosine kinases, immune checkpoints, and cell-surface phosphatases. Binders exhibit nanomolar affinity, target specificity, and functional activity in laboratory assays, per the ESMC and ESMFold2 paper titled ["Language Modeling Materializes a World Model of Protein Biology"](https://biohub.ai/papers/esm_protein.pdf).

> **Model size tradeoff:** Biohub's flagship checkpoints (`ESMFold2-Experimental-Fast`/`ESMFold2-Experimental`) are paired with the 6B-parameter ESMC language model — a ~24GB download/VRAM commitment for the shared LM alone. To avoid that, `binder_design.py` in this folder is configured to use Biohub's smaller scaling-study checkpoints instead (`ESMFold2-Experimental-Fast-base300M-step1500k` for the inversion model, `-step1000k`/`-step1500k` as critics), paired with the 300M ESMC. This is ~20x smaller, but per Biohub's own scaling-law results, designs from these smaller/earlier checkpoints will likely be lower quality (worse success rate, less accurate structures) than the flagship. If quality matters more than local resource use, switch back to the flagship names and accept the 6B download (or use Modal instead).

**You'll need:** a target protein sequence (or pick one of the built-in presets), and a local GPU.

**You'll get:** a file of top-ranked designed binder sequences, plus 3D structures of the predicted complexes that you can view in the notebook.

**Workflow:**
1. **Setup** (one-time): install dependencies, load the model ensemble onto the GPU
2. **Try one job**: pick a target and binder type, run a single design end-to-end as a sanity check
3. **Run a sweep**: run many seeds sequentially to produce real candidates
4. **Pick the designs to order**: filter and rank, save the shortlist

### 1. Setup

- note that waluigi:8890 is for esm2 (other 2 r for boltzgen)

In [2]:
# Dependencies are installed into the venv by start_jupyter_esmfold2.bash
# (via `uv pip install`), not here. Bare `! pip install` in this kernel can
# resolve to the system pip instead of the venv's (uv-created venvs don't
# ship a `pip` binary), which silently installs into the wrong place. If you
# ever do need to install something from a cell, use sys.executable:
import sys
print(sys.executable)
# !{sys.executable} -m pip install <package>

/home/bridget/esmfold2_venv/bin/python

In [3]:
%cd ~/notebooks

/home/bridget/notebooks

### Imports

In [4]:
from itertools import product
from pathlib import Path

import pandas as pd
import py3Dmol
from Bio.SeqUtils.ProtParam import ProteinAnalysis
from tqdm.auto import tqdm

from binder_design import ESMFold2Design

ESMC: transformer_engine is not installed; falling back to pure-PyTorch LayerNorm+Linear / LayerNorm+MLP. Outputs will differ numerically — measured on the unnormalized residual stream (before the final LayerNorm), ~O(10) max-diff in fp32 and ~O(100) in bf16; after the final LayerNorm these shrink to a few ULP and perplexity stays within rounding noise. Install with `pip install transformer-engine[pytorch]` to enable fused fp32-reduction LayerNorm.
ESMC: neither xformers nor flash-attn is installed; falling back to PyTorch ``F.scaled_dot_product_attention``. The attention reduction order in bf16 differs from a fused kernel by ~1 bf16 ULP per attention block; compounded across the 80-block stack this reaches ~O(100) max-diff on the unnormalized residual stream. Install xformers (preferred) with `pip install xformers` for a fused attention kernel.
ESMC: flash-attn rotary kernel not installed; falling back to pure-PyTorch RoPE. For faster GPU inference run `pip install flash-attn`.

🚨 No checkpoint found for ESMCForSequenceClassification.forward. Please add a `checkpoint` arg to `auto_docstring` or add one in ESMCConfig's docstring
🚨 No checkpoint found for ESMCForTokenClassification.forward. Please add a `checkpoint` arg to `auto_docstring` or add one in ESMCConfig's docstring

In [5]:
import importlib
import binder_design
importlib.reload(binder_design)
from binder_design import ESMFold2Design

### App setup

`ESMFold2Design()` loads the full model ensemble (inversion models, critics, ESMC) directly onto this machine's GPU. This takes a few minutes and a lot of VRAM — do it once and reuse the `app` object for every design call below, rather than re-instantiating it.

`use_scaling_critics=False` is the default. Setting it to `True` adds extra critic models from the paper that improve selection at the cost of more compute and VRAM per job — likely not viable locally unless you have a lot of headroom.

In [9]:
app = ESMFold2Design()
# Set 'use_scaling_critics' to evaluate with the additional critics.
app.load(use_scaling_critics=False)

`torch_dtype` is deprecated! Use `dtype` instead!

## 2. Try one design job

Run a single job end-to-end before launching a sweep. This is a sanity check that everything is wired up and that the target/scaffold combo you've chosen produces a sensible complex.

Pick **one** of the two options below and run only that cell. (They both define `best_sequences`/`trajectory`/`critic_results`, so running both back-to-back overwrites the first.)

**Option 1** uses a built-in target and binder scaffold. Available targets: `ctla4`, `egfr`, `pdgfrb`, `pd-l1`, `cd45`. Available binder types: `minibinder`, `trastuzumab_framework_vhvl` (an antibody scaffold). Easiest if your target is one of the built-ins.

**Option 2** takes your own target sequence and binder scaffold. In the binder scaffold, `#` means "design this position" and any amino acid letter means "keep this position fixed." For example:
- `"#" * 60` designs a fully free 60-residue minibinder
- A trastuzumab-style antibody scaffold (shown below) fixes the framework regions and lets the model design the CDR loops

If you're designing an antibody, pass `is_antibody=True` so the selection step later uses the antibody-appropriate scoring.

This runs synchronously on your local GPU and blocks until finished — you'll see per-step loss logging printed directly below the cell.

In [ ]:
# ---- Option 1: Use presets. ----
# Relies on the registry in binder_design.py::{TARGET_SEQUENCES,BINDER_PROMPT_FACTORIES}, which can be modified.
# best_sequences, trajectory, critic_results = app.design(target_name="ctla4", binder_name="minibinder")

In [10]:
# ---- Option 2: Provide your own sequences. ----
# Our s100b sequence crop.
s100b_sequence = "SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEEIKEQEVVDKVMETLDNDGDGECDFQEFMAFVAMVTTACHEFFEHE"

best_sequences, trajectory, critic_results = app.design(
    target_sequence=s100b_sequence,
    binder_sequence="#" * 50,   # 50 fully-designed residues
)
print("Best sequences:", best_sequences)

2026-06-26 23:34:49,192 INFO: Enabling RDKit 2026.03.3 jupyter extensions

Loading CCD dictionary from /home/bridget/.cache/huggingface/hub/models--biohub--ESMFold2/snapshots/1ebf0e3481a5184eb6171d40615c79e384b48796/ccd.pkl

2026-06-26 23:34:55,954 INFO:   step   0  |  intra_contact_loss=4.5801  inter_contact_loss=3.7846  glob_loss=4.5647  total_loss=8.2359  plm_loss=3.1406  T=0.9999
2026-06-26 23:34:59,221 INFO:   step   5  |  intra_contact_loss=3.8247  inter_contact_loss=3.4136  glob_loss=3.2798  total_loss=7.4782  plm_loss=3.2031  T=0.9961
2026-06-26 23:35:02,353 INFO:   step  10  |  intra_contact_loss=3.5552  inter_contact_loss=3.4194  glob_loss=2.5441  total_loss=7.4961  plm_loss=3.5000  T=0.9869
2026-06-26 23:35:05,669 INFO:   step  15  |  intra_contact_loss=3.5194  inter_contact_loss=3.2648  glob_loss=2.5948  total_loss=7.4267  plm_loss=3.5156  T=0.9725
2026-06-26 23:35:08,803 INFO:   step  20  |  intra_contact_loss=3.4714  inter_contact_loss=3.3161  glob_loss=2.3497  total_loss=7.4887  plm_loss=3.6250  T=0.9529
2026-06-26 23:35:11,955 INFO:   step  25  |  intra_contact_loss=3.5414  inter_contact_loss=3.3171  glob_loss=2.4535  total_loss=7.5137  plm_loss=3.5938  T=0.9284
2026-06-26 23:35:15,108 INFO:   step  30  |  intra_contact_loss=3.3653  inter_contact_loss=3.3386  glob_loss=2.2117  total_loss=7.2943  plm_loss=3.5000  T=0.8993
2026-06-26 23:35:18,252 INFO:   step  35  |  intra_contact_loss=3.3013  inter_contact_loss=3.2509  glob_loss=2.1848  total_loss=7.0724  plm_loss=3.3594  T=0.8658
2026-06-26 23:35:21,396 INFO:   step  40  |  intra_contact_loss=3.3416  inter_contact_loss=3.2429  glob_loss=2.1771  total_loss=7.3058  plm_loss=3.5781  T=0.8284
2026-06-26 23:35:24,712 INFO:   step  45  |  intra_contact_loss=3.2696  inter_contact_loss=3.1390  glob_loss=1.9231  total_loss=6.8077  plm_loss=3.2188  T=0.7875
2026-06-26 23:35:27,866 INFO:   step  50  |  intra_contact_loss=3.3650  inter_contact_loss=3.3941  glob_loss=2.0420  total_loss=6.9442  plm_loss=3.1562  T=0.7435
2026-06-26 23:35:31,017 INFO:   step  55  |  intra_contact_loss=3.1926  inter_contact_loss=3.2434  glob_loss=1.9461  total_loss=6.8572  plm_loss=3.2500  T=0.6968
2026-06-26 23:35:34,169 INFO:   step  60  |  intra_contact_loss=3.2378  inter_contact_loss=3.2932  glob_loss=2.0139  total_loss=6.4339  plm_loss=2.7656  T=0.6481
2026-06-26 23:35:37,321 INFO:   step  65  |  intra_contact_loss=3.2190  inter_contact_loss=3.2666  glob_loss=1.8019  total_loss=6.3844  plm_loss=2.7812  T=0.5978
2026-06-26 23:35:40,677 INFO:   step  70  |  intra_contact_loss=3.1956  inter_contact_loss=3.1108  glob_loss=1.8842  total_loss=6.0925  plm_loss=2.5625  T=0.5464
2026-06-26 23:35:43,839 INFO:   step  75  |  intra_contact_loss=3.2220  inter_contact_loss=3.1616  glob_loss=1.7904  total_loss=5.9874  plm_loss=2.4375  T=0.4946
2026-06-26 23:35:47,003 INFO:   step  80  |  intra_contact_loss=3.2990  inter_contact_loss=3.2482  glob_loss=2.0677  total_loss=6.1403  plm_loss=2.4531  T=0.4430
2026-06-26 23:35:50,169 INFO:   step  85  |  intra_contact_loss=3.2140  inter_contact_loss=3.2591  glob_loss=1.7708  total_loss=5.9657  plm_loss=2.3750  T=0.3920
2026-06-26 23:35:53,498 INFO:   step  90  |  intra_contact_loss=3.3020  inter_contact_loss=3.3423  glob_loss=1.7821  total_loss=5.7880  plm_loss=2.1094  T=0.3422
2026-06-26 23:35:56,664 INFO:   step  95  |  intra_contact_loss=3.2659  inter_contact_loss=3.2754  glob_loss=1.7768  total_loss=5.9385  plm_loss=2.3125  T=0.2942
2026-06-26 23:35:59,847 INFO:   step 100  |  intra_contact_loss=3.0969  inter_contact_loss=3.2398  glob_loss=1.7106  total_loss=5.4792  plm_loss=1.9688  T=0.2486
2026-06-26 23:36:03,012 INFO:   step 105  |  intra_contact_loss=3.1734  inter_contact_loss=3.3485  glob_loss=1.8722  total_loss=5.5729  plm_loss=1.9375  T=0.2057
2026-06-26 23:36:06,345 INFO:   step 110  |  intra_contact_loss=3.1895  inter_contact_loss=3.3269  glob_loss=1.7864  total_loss=5.6311  plm_loss=2.0156  T=0.1661
2026-06-26 23:36:09,512 INFO:   step 115  |  intra_contact_loss=3.1531  inter_contact_loss=3.0795  glob_loss=1.6504  total_loss=5.4073  plm_loss=1.9609  T=0.1303
2026-06-26 23:36:12,680 INFO:   step 120  |  intra_contact_loss=3.2129  inter_contact_loss=3.2810  glob_loss=1.8417  total_loss=5.5216  plm_loss=1.9062  T=0.0985
2026-06-26 23:36:16,014 INFO:   step 125  |  intra_contact_loss=3.1412  inter_contact_loss=3.3089  glob_loss=1.7627  total_loss=5.4448  plm_loss=1.8672  T=0.0712
2026-06-26 23:36:19,707 INFO:   step 130  |  intra_contact_loss=3.1500  inter_contact_loss=3.3335  glob_loss=1.7314  total_loss=5.4318  plm_loss=1.8438  T=0.0487
2026-06-26 23:36:25,489 INFO:   step 135  |  intra_contact_loss=3.1703  inter_contact_loss=3.1827  glob_loss=1.5391  total_loss=5.4374  plm_loss=1.9531  T=0.0311
2026-06-26 23:36:31,295 INFO:   step 140  |  intra_contact_loss=3.1596  inter_contact_loss=3.2329  glob_loss=1.7751  total_loss=5.2309  plm_loss=1.6797  T=0.0188
2026-06-26 23:36:37,249 INFO:   step 145  |  intra_contact_loss=3.1216  inter_contact_loss=3.2326  glob_loss=1.7815  total_loss=5.6115  plm_loss=2.0781  T=0.0117
2026-06-26 23:36:41,884 WARNING: iptm never computed for batch 0; using last-step sequence as fallback

Best sequences: ['SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEEIKEQEVVDKVMETLDNDGDGECDFQEFMAFVAMVTTACHEFFEHE|LLLLLRGGGAVAALLAALVVLLVPALGGGGSLAAVAAAAVKVVVWLVQLL']

In [11]:
# ---- Inspect result ----
df = pd.DataFrame(critic_results)
df.drop(columns=["logits", "complex"])

,is_antibody,critic_name,batch_idx,designed_sequence,final_loss,iptm,distogram_iptm_proxy,cdr_distogram_iptm_proxy
0,False,ESMFold2-Experimental-Fast-base300M-step1000k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.523508,None,0.336345,NaN
1,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.523508,None,0.356215,NaN

In [12]:
# ---- Visualize ----
protein_complex = (
    df[df.critic_name.eq("ESMFold2-Experimental-Fast-base300M-step1500k")].iloc[0].complex
)
(
    py3Dmol.view(width=600, height=600)
    .addModel(protein_complex.to_pdb_string(), "pdb")
    .setStyle({"chain": "A"}, {"cartoon": {"color": "green"}})  # pyright: ignore
    .setStyle({"chain": "B"}, {"cartoon": {"color": "cyan"}})  # pyright: ignore
    .addStyle(  # pyright: ignore
        {"not": {"atom": ["N", "C", "O"]}},
        {"stick": {"colorscheme": "default", "radius": 0.2}},
    )
    .center()  # pyright: ignore
    .zoomTo()  # pyright: ignore
)

In [20]:
# ---- Visualize top 3 designs ----
TOP_SEEDS = [27, 3, 2]
CRITIC = "ESMFold2-Experimental-Fast-base300M-step1500k"

for seed in TOP_SEEDS:
    row = df_result[(df_result.seed == seed) & (df_result.critic_name == CRITIC)].iloc[0]
    scores = df_select.xs(seed, level=1) if seed in df_select.index.get_level_values(1) else None
    binder_seq = row.designed_sequence.split("|")[1]
    proxy = row.distogram_iptm_proxy
    print(f"--- Seed {seed} | iptm_proxy={proxy:.3f} | binder: {binder_seq}")
    if scores is not None and not scores.empty:
        s = scores.iloc[0]
        print(f"    site1={s.contact_site1_helix:.2f}  site2={s.contact_site2_loop:.2f}  site3={s.contact_site3_hydrophobic:.2f}  avoid={s.contact_avoid:.2f}")
    display(
        py3Dmol.view(width=500, height=400)
        .addModel(row.complex.to_pdb_string(), "pdb")
        .setStyle({"chain": "A"}, {"cartoon": {"color": "green"}})
        .setStyle({"chain": "B"}, {"cartoon": {"color": "cyan"}})
        .addStyle({"not": {"atom": ["N", "C", "O"]}}, {"stick": {"colorscheme": "default", "radius": 0.2}})
        .center()
        .zoomTo()
    )

--- Seed 27 | iptm_proxy=0.412 | binder: SLLLLLLKLARKLVQSGNLALAVLVALLAVLLLGGNPQLAVAVVAAVLLQ

--- Seed 3 | iptm_proxy=0.352 | binder: LLLLLLLVLVTAVHTALTALTLLGNGGGLLLALLLLLLLLALAVVLLLLV

--- Seed 2 | iptm_proxy=0.479 | binder: SSLLKMLLLLLLLLLVLKYLYQNGLLSPSQYQRYKSFLLGMLKMLLRLLS

## 3. Run a sweep for real designs
For real candidates worth ordering, sweep across many seeds (and optionally multiple targets, binder types, or lengths) and select the best.

Edit `line_sweeps` below to define your campaign. Each key is a sweep axis; the notebook runs one job per combination of values. Unlike the Modal version, this runs **sequentially on your local GPU** — there's no cloud parallelism, so wall-clock time is roughly (per-job time from section 2) × (number of jobs). Start with a small number of seeds to estimate timing before committing to a big sweep.

**Before you click Run on the Launch cell, check the printed shape of the dataframe and confirm it's the number of jobs you intended.**

In [13]:
# ---- Config ----
save_dir = Path("sweep")
save_dir.mkdir(exist_ok=True)

s100b_sequence = "SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEEIKEQEVVDKVMETLDNDGDGECDFQEFMAFVAMVTTACHEFFEHE"

line_sweeps = dict(
    target_name=[None],
    target_sequence=[s100b_sequence],
    binder_name=[None],
    binder_sequence=["#" * 50],   # 50 fully-designed residues
    use_scaling_critics=[False],  # must match app.load() above
    seed=list(range(50)),          # 50 seeds → 50 designs (~3 hrs on single GPU)
    batch_size=[1],
)
df = pd.DataFrame(product(*line_sweeps.values()), columns=list(line_sweeps.keys()))
display(df.head(2))
df.shape

,target_name,target_sequence,binder_name,binder_sequence,use_scaling_critics,seed,batch_size
0,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,##############################################...,False,0,1
1,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,##############################################...,False,1,1

(50, 7)

In [14]:
# ---- Run sweep (sequential — single local GPU, no cloud parallelism) ----
result_dfs = []
failures = []
for row in tqdm(list(df.itertuples()), desc="sweep"):
    try:
        for m in app.hf_critic_models.values():
            m.cuda()
        best_sequences, trajectory, critic_results = app.design(
            target_name=row.target_name,
            target_sequence=row.target_sequence,
            binder_name=row.binder_name,
            binder_sequence=row.binder_sequence,
            seed=row.seed,
            batch_size=row.batch_size,
        )
    except Exception as e:
        failures.append((row.Index, str(e)))
        continue
    result_df = pd.DataFrame(critic_results)
    for col in (
        "target_name", "target_sequence", "binder_name", "binder_sequence",
        "use_scaling_critics", "seed", "batch_size",
    ):
        result_df[col] = getattr(row, col)
    result_dfs.append(result_df)

df_result = pd.concat(result_dfs, ignore_index=True)
df_result.drop(columns=["complex", "logits"], errors="ignore").to_parquet(
    save_dir / "manifest.parquet", index=False
)
print(f"Completed {len(df) - len(failures)}/{len(df)} jobs -> {len(df_result)} result rows")
if failures:
    print(f"{len(failures)} jobs failed, e.g.: {failures[0]}")

sweep:   0%|          | 0/50 [00:00<?, ?it/s]

2026-06-26 23:38:11,810 INFO:   step   0  |  intra_contact_loss=4.5812  inter_contact_loss=3.7937  glob_loss=4.5617  total_loss=8.2404  plm_loss=3.1406  T=0.9999
2026-06-26 23:38:14,943 INFO:   step   5  |  intra_contact_loss=3.6819  inter_contact_loss=3.4709  glob_loss=2.9694  total_loss=7.5297  plm_loss=3.3594  T=0.9961
2026-06-26 23:38:18,277 INFO:   step  10  |  intra_contact_loss=3.4249  inter_contact_loss=3.4562  glob_loss=2.3262  total_loss=7.2808  plm_loss=3.3750  T=0.9869
2026-06-26 23:38:21,417 INFO:   step  15  |  intra_contact_loss=3.4001  inter_contact_loss=3.3118  glob_loss=2.3847  total_loss=7.4110  plm_loss=3.5781  T=0.9725
2026-06-26 23:38:24,560 INFO:   step  20  |  intra_contact_loss=3.4901  inter_contact_loss=3.4727  glob_loss=2.4055  total_loss=7.4312  plm_loss=3.4688  T=0.9529
2026-06-26 23:38:27,923 INFO:   step  25  |  intra_contact_loss=3.4835  inter_contact_loss=3.4956  glob_loss=2.4083  total_loss=7.2993  plm_loss=3.3281  T=0.9284
2026-06-26 23:38:31,077 INFO:   step  30  |  intra_contact_loss=3.3938  inter_contact_loss=3.5195  glob_loss=2.2305  total_loss=7.2777  plm_loss=3.3750  T=0.8993
2026-06-26 23:38:34,235 INFO:   step  35  |  intra_contact_loss=3.2878  inter_contact_loss=3.2677  glob_loss=2.1398  total_loss=6.8620  plm_loss=3.1562  T=0.8658
2026-06-26 23:38:37,396 INFO:   step  40  |  intra_contact_loss=3.2253  inter_contact_loss=3.2566  glob_loss=2.1177  total_loss=6.8833  plm_loss=3.2188  T=0.8284
2026-06-26 23:38:40,558 INFO:   step  45  |  intra_contact_loss=3.0634  inter_contact_loss=2.9591  glob_loss=2.0126  total_loss=6.5544  plm_loss=3.1406  T=0.7875
2026-06-26 23:38:43,720 INFO:   step  50  |  intra_contact_loss=3.0186  inter_contact_loss=3.0506  glob_loss=2.0752  total_loss=6.3871  plm_loss=2.9375  T=0.7435
2026-06-26 23:38:47,056 INFO:   step  55  |  intra_contact_loss=3.0668  inter_contact_loss=3.2056  glob_loss=2.0942  total_loss=6.5238  plm_loss=2.9688  T=0.6968
2026-06-26 23:38:50,238 INFO:   step  60  |  intra_contact_loss=3.1135  inter_contact_loss=3.3026  glob_loss=2.1086  total_loss=6.4735  plm_loss=2.8438  T=0.6481
2026-06-26 23:38:53,405 INFO:   step  65  |  intra_contact_loss=3.0021  inter_contact_loss=2.9430  glob_loss=1.9958  total_loss=6.2780  plm_loss=2.9062  T=0.5978
2026-06-26 23:38:56,576 INFO:   step  70  |  intra_contact_loss=3.0788  inter_contact_loss=3.2548  glob_loss=1.9699  total_loss=6.3264  plm_loss=2.7656  T=0.5464
2026-06-26 23:38:59,765 INFO:   step  75  |  intra_contact_loss=2.8630  inter_contact_loss=3.2003  glob_loss=1.8504  total_loss=5.9642  plm_loss=2.5625  T=0.4946
2026-06-26 23:39:03,105 INFO:   step  80  |  intra_contact_loss=2.8733  inter_contact_loss=3.1747  glob_loss=2.0022  total_loss=6.1901  plm_loss=2.7656  T=0.4430
2026-06-26 23:39:06,280 INFO:   step  85  |  intra_contact_loss=2.9590  inter_contact_loss=3.2454  glob_loss=1.9774  total_loss=6.0445  plm_loss=2.5469  T=0.3920
2026-06-26 23:39:09,472 INFO:   step  90  |  intra_contact_loss=2.8994  inter_contact_loss=2.9851  glob_loss=1.9605  total_loss=5.7249  plm_loss=2.3906  T=0.3422
2026-06-26 23:39:12,648 INFO:   step  95  |  intra_contact_loss=2.8871  inter_contact_loss=3.0853  glob_loss=1.8956  total_loss=5.8497  plm_loss=2.4844  T=0.2942
2026-06-26 23:39:15,991 INFO:   step 100  |  intra_contact_loss=2.8597  inter_contact_loss=3.0779  glob_loss=1.9098  total_loss=5.6632  plm_loss=2.3125  T=0.2486
2026-06-26 23:39:19,169 INFO:   step 105  |  intra_contact_loss=2.7346  inter_contact_loss=2.9409  glob_loss=1.9014  total_loss=5.5462  plm_loss=2.3281  T=0.2057
2026-06-26 23:39:22,347 INFO:   step 110  |  intra_contact_loss=3.0772  inter_contact_loss=3.3489  glob_loss=2.0276  total_loss=5.8842  plm_loss=2.2656  T=0.1661
2026-06-26 23:39:25,522 INFO:   step 115  |  intra_contact_loss=2.8570  inter_contact_loss=3.0048  glob_loss=1.9126  total_loss=5.4384  plm_loss=2.1250  T=0.1303
2026-06-26 23:39:28,864 INFO:   step 120  |  intra_contact_loss=2.8648  inter_contact_loss=3.0052  glob_loss=1.9161  total_loss=5.5682  plm_loss=2.2500  T=0.0985
2026-06-26 23:39:32,044 INFO:   step 125  |  intra_contact_loss=2.9159  inter_contact_loss=3.1616  glob_loss=1.9539  total_loss=5.4452  plm_loss=2.0156  T=0.0712
2026-06-26 23:39:35,758 INFO:   step 130  |  intra_contact_loss=2.9206  inter_contact_loss=3.2603  glob_loss=1.9143  total_loss=5.6296  plm_loss=2.1562  T=0.0487
2026-06-26 23:39:41,594 INFO:   step 135  |  intra_contact_loss=2.8120  inter_contact_loss=3.2218  glob_loss=1.9803  total_loss=5.4130  plm_loss=2.0000  T=0.0311
2026-06-26 23:39:47,611 INFO:   step 140  |  intra_contact_loss=2.6439  inter_contact_loss=2.8714  glob_loss=1.9363  total_loss=4.9262  plm_loss=1.7812  T=0.0188
2026-06-26 23:39:53,416 INFO:   step 145  |  intra_contact_loss=3.0055  inter_contact_loss=3.3841  glob_loss=1.8689  total_loss=5.5217  plm_loss=1.9531  T=0.0117
2026-06-26 23:39:58,066 WARNING: iptm never computed for batch 0; using last-step sequence as fallback
2026-06-26 23:40:04,385 INFO:   step   0  |  intra_contact_loss=4.2521  inter_contact_loss=3.2667  glob_loss=3.5260  total_loss=7.5739  plm_loss=3.1094  T=0.9999
2026-06-26 23:40:07,734 INFO:   step   5  |  intra_contact_loss=3.6197  inter_contact_loss=3.4491  glob_loss=2.6167  total_loss=7.1671  plm_loss=3.1094  T=0.9961
2026-06-26 23:40:10,919 INFO:   step  10  |  intra_contact_loss=3.6085  inter_contact_loss=3.5122  glob_loss=2.6110  total_loss=7.3795  plm_loss=3.2969  T=0.9869
2026-06-26 23:40:14,121 INFO:   step  15  |  intra_contact_loss=3.7677  inter_contact_loss=3.3783  glob_loss=2.7950  total_loss=7.6007  plm_loss=3.4688  T=0.9725
2026-06-26 23:40:17,307 INFO:   step  20  |  intra_contact_loss=3.5269  inter_contact_loss=3.4881  glob_loss=2.3771  total_loss=7.6548  plm_loss=3.6719  T=0.9529
2026-06-26 23:40:20,660 INFO:   step  25  |  intra_contact_loss=3.3857  inter_contact_loss=3.3684  glob_loss=2.1864  total_loss=7.6737  plm_loss=3.8594  T=0.9284
2026-06-26 23:40:23,864 INFO:   step  30  |  intra_contact_loss=3.3127  inter_contact_loss=3.3776  glob_loss=2.0903  total_loss=7.4820  plm_loss=3.7188  T=0.8993
2026-06-26 23:40:27,070 INFO:   step  35  |  intra_contact_loss=3.2477  inter_contact_loss=3.3911  glob_loss=2.0357  total_loss=7.5390  plm_loss=3.8125  T=0.8658
2026-06-26 23:40:30,257 INFO:   step  40  |  intra_contact_loss=3.2674  inter_contact_loss=3.3194  glob_loss=1.9963  total_loss=7.1458  plm_loss=3.4531  T=0.8284
2026-06-26 23:40:33,653 INFO:   step  45  |  intra_contact_loss=2.9892  inter_contact_loss=3.1194  glob_loss=2.0028  total_loss=6.5174  plm_loss=3.0625  T=0.7875
2026-06-26 23:40:36,842 INFO:   step  50  |  intra_contact_loss=3.1391  inter_contact_loss=3.1904  glob_loss=1.9740  total_loss=6.6845  plm_loss=3.1250  T=0.7435
2026-06-26 23:40:40,030 INFO:   step  55  |  intra_contact_loss=3.1087  inter_contact_loss=3.3114  glob_loss=1.9082  total_loss=7.0448  plm_loss=3.4531  T=0.6968
2026-06-26 23:40:43,388 INFO:   step  60  |  intra_contact_loss=3.0625  inter_contact_loss=3.3404  glob_loss=1.9373  total_loss=6.3233  plm_loss=2.7344  T=0.6481
2026-06-26 23:40:46,588 INFO:   step  65  |  intra_contact_loss=2.9838  inter_contact_loss=3.2876  glob_loss=1.9425  total_loss=6.6023  plm_loss=3.0781  T=0.5978
2026-06-26 23:40:49,776 INFO:   step  70  |  intra_contact_loss=3.0882  inter_contact_loss=3.2948  glob_loss=1.9667  total_loss=6.4755  plm_loss=2.8906  T=0.5464
2026-06-26 23:40:53,161 INFO:   step  75  |  intra_contact_loss=3.0881  inter_contact_loss=3.3738  glob_loss=1.8675  total_loss=5.9482  plm_loss=2.3438  T=0.4946
2026-06-26 23:40:56,351 INFO:   step  80  |  intra_contact_loss=3.1784  inter_contact_loss=3.3825  glob_loss=1.9460  total_loss=6.1384  plm_loss=2.4688  T=0.4430
2026-06-26 23:40:59,539 INFO:   step  85  |  intra_contact_loss=3.0345  inter_contact_loss=3.3251  glob_loss=1.9334  total_loss=5.3477  plm_loss=1.7812  T=0.3920
2026-06-26 23:41:02,898 INFO:   step  90  |  intra_contact_loss=2.9341  inter_contact_loss=3.4167  glob_loss=1.9400  total_loss=5.6728  plm_loss=2.1094  T=0.3422
2026-06-26 23:41:06,090 INFO:   step  95  |  intra_contact_loss=3.0408  inter_contact_loss=3.3094  glob_loss=1.8619  total_loss=5.4693  plm_loss=1.9219  T=0.2942
2026-06-26 23:41:09,279 INFO:   step 100  |  intra_contact_loss=2.8321  inter_contact_loss=3.3790  glob_loss=1.9540  total_loss=5.9338  plm_loss=2.4375  T=0.2486
2026-06-26 23:41:12,654 INFO:   step 105  |  intra_contact_loss=2.7411  inter_contact_loss=3.2260  glob_loss=1.9011  total_loss=5.5669  plm_loss=2.2031  T=0.2057
2026-06-26 23:41:15,845 INFO:   step 110  |  intra_contact_loss=2.9585  inter_contact_loss=3.3373  glob_loss=1.9394  total_loss=5.5982  plm_loss=2.0625  T=0.1661
2026-06-26 23:41:19,036 INFO:   step 115  |  intra_contact_loss=2.9359  inter_contact_loss=3.2743  glob_loss=1.8898  total_loss=5.0299  plm_loss=1.5469  T=0.1303
2026-06-26 23:41:22,438 INFO:   step 120  |  intra_contact_loss=2.7529  inter_contact_loss=3.3283  glob_loss=1.9043  total_loss=4.6090  plm_loss=1.1875  T=0.0985
2026-06-26 23:41:25,632 INFO:   step 125  |  intra_contact_loss=2.8173  inter_contact_loss=3.3764  glob_loss=1.9721  total_loss=5.2804  plm_loss=1.7891  T=0.0712
2026-06-26 23:41:29,351 INFO:   step 130  |  intra_contact_loss=2.8336  inter_contact_loss=3.3427  glob_loss=1.9217  total_loss=4.9959  plm_loss=1.5234  T=0.0487
2026-06-26 23:41:35,359 INFO:   step 135  |  intra_contact_loss=2.8648  inter_contact_loss=3.3901  glob_loss=1.9074  total_loss=5.4542  plm_loss=1.9453  T=0.0311
2026-06-26 23:41:41,197 INFO:   step 140  |  intra_contact_loss=2.8054  inter_contact_loss=3.3734  glob_loss=1.9609  total_loss=4.7159  plm_loss=1.2344  T=0.0188
2026-06-26 23:41:47,019 INFO:   step 145  |  intra_contact_loss=2.8294  inter_contact_loss=3.3546  glob_loss=1.8960  total_loss=5.2681  plm_loss=1.7969  T=0.0117
2026-06-26 23:41:51,893 WARNING: iptm never computed for batch 0; using last-step sequence as fallback
2026-06-26 23:41:58,217 INFO:   step   0  |  intra_contact_loss=4.3468  inter_contact_loss=3.8011  glob_loss=4.0799  total_loss=8.0149  plm_loss=3.1250  T=0.9999
2026-06-26 23:42:01,408 INFO:   step   5  |  intra_contact_loss=3.4584  inter_contact_loss=3.4579  glob_loss=2.3155  total_loss=7.3588  plm_loss=3.4375  T=0.9961
2026-06-26 23:42:04,600 INFO:   step  10  |  intra_contact_loss=3.2585  inter_contact_loss=3.4840  glob_loss=2.1728  total_loss=7.3527  plm_loss=3.5469  T=0.9869
2026-06-26 23:42:07,958 INFO:   step  15  |  intra_contact_loss=3.2645  inter_contact_loss=3.5356  glob_loss=2.1483  total_loss=7.7672  plm_loss=3.9375  T=0.9725
2026-06-26 23:42:11,148 INFO:   step  20  |  intra_contact_loss=3.2240  inter_contact_loss=3.4394  glob_loss=2.0775  total_loss=8.2785  plm_loss=4.5312  T=0.9529
2026-06-26 23:42:14,337 INFO:   step  25  |  intra_contact_loss=2.8959  inter_contact_loss=3.1493  glob_loss=2.0239  total_loss=7.5211  plm_loss=4.0938  T=0.9284
2026-06-26 23:42:17,697 INFO:   step  30  |  intra_contact_loss=2.9268  inter_contact_loss=3.3914  glob_loss=2.0185  total_loss=7.3753  plm_loss=3.8125  T=0.8993
2026-06-26 23:42:20,888 INFO:   step  35  |  intra_contact_loss=2.9921  inter_contact_loss=3.4826  glob_loss=2.0046  total_loss=7.2164  plm_loss=3.5781  T=0.8658
2026-06-26 23:42:24,076 INFO:   step  40  |  intra_contact_loss=2.6497  inter_contact_loss=3.3630  glob_loss=1.9778  total_loss=7.2769  plm_loss=3.8750  T=0.8284
2026-06-26 23:42:27,442 INFO:   step  45  |  intra_contact_loss=2.6790  inter_contact_loss=3.3355  glob_loss=1.9232  total_loss=6.8450  plm_loss=3.4531  T=0.7875
2026-06-26 23:42:30,631 INFO:   step  50  |  intra_contact_loss=2.6933  inter_contact_loss=3.1935  glob_loss=1.9164  total_loss=6.4360  plm_loss=3.1094  T=0.7435
2026-06-26 23:42:33,822 INFO:   step  55  |  intra_contact_loss=2.6409  inter_contact_loss=3.1793  glob_loss=1.9412  total_loss=6.5327  plm_loss=3.2344  T=0.6968
2026-06-26 23:42:37,013 INFO:   step  60  |  intra_contact_loss=2.4822  inter_contact_loss=3.2724  glob_loss=1.8985  total_loss=6.1945  plm_loss=2.9375  T=0.6481
2026-06-26 23:42:40,207 INFO:   step  65  |  intra_contact_loss=2.4577  inter_contact_loss=3.3069  glob_loss=1.8873  total_loss=6.5566  plm_loss=3.2969  T=0.5978
2026-06-26 23:42:43,398 INFO:   step  70  |  intra_contact_loss=2.4395  inter_contact_loss=3.3155  glob_loss=1.9175  total_loss=5.7454  plm_loss=2.4844  T=0.5464
2026-06-26 23:42:46,762 INFO:   step  75  |  intra_contact_loss=2.3704  inter_contact_loss=3.1542  glob_loss=1.8929  total_loss=5.7815  plm_loss=2.6406  T=0.4946
2026-06-26 23:42:49,954 INFO:   step  80  |  intra_contact_loss=2.5348  inter_contact_loss=3.4141  glob_loss=1.8804  total_loss=5.7724  plm_loss=2.4219  T=0.4430
2026-06-26 23:42:53,166 INFO:   step  85  |  intra_contact_loss=2.3425  inter_contact_loss=3.1048  glob_loss=1.8460  total_loss=5.7179  plm_loss=2.6250  T=0.3920
2026-06-26 23:42:56,361 INFO:   step  90  |  intra_contact_loss=2.3804  inter_contact_loss=3.1962  glob_loss=1.8741  total_loss=5.6944  plm_loss=2.5312  T=0.3422
2026-06-26 23:42:59,553 INFO:   step  95  |  intra_contact_loss=2.3264  inter_contact_loss=3.1254  glob_loss=1.8836  total_loss=5.5714  plm_loss=2.4688  T=0.2942
2026-06-26 23:43:02,914 INFO:   step 100  |  intra_contact_loss=2.3770  inter_contact_loss=3.0734  glob_loss=1.8793  total_loss=5.3198  plm_loss=2.2188  T=0.2486
2026-06-26 23:43:06,108 INFO:   step 105  |  intra_contact_loss=2.3754  inter_contact_loss=3.1030  glob_loss=1.8807  total_loss=5.3810  plm_loss=2.2656  T=0.2057
2026-06-26 23:43:09,300 INFO:   step 110  |  intra_contact_loss=2.3416  inter_contact_loss=3.0889  glob_loss=1.8785  total_loss=5.5284  plm_loss=2.4375  T=0.1661
2026-06-26 23:43:12,493 INFO:   step 115  |  intra_contact_loss=2.3695  inter_contact_loss=2.9459  glob_loss=1.9019  total_loss=5.3506  plm_loss=2.3125  T=0.1303
2026-06-26 23:43:15,854 INFO:   step 120  |  intra_contact_loss=2.4023  inter_contact_loss=2.9982  glob_loss=1.9005  total_loss=5.1116  plm_loss=2.0312  T=0.0985
2026-06-26 23:43:19,046 INFO:   step 125  |  intra_contact_loss=2.3542  inter_contact_loss=3.1022  glob_loss=1.8443  total_loss=5.4564  plm_loss=2.3594  T=0.0712
2026-06-26 23:43:22,774 INFO:   step 130  |  intra_contact_loss=2.3164  inter_contact_loss=3.1172  glob_loss=1.8574  total_loss=5.1508  plm_loss=2.0625  T=0.0487
2026-06-26 23:43:28,635 INFO:   step 135  |  intra_contact_loss=2.3570  inter_contact_loss=3.0274  glob_loss=1.8563  total_loss=5.4385  plm_loss=2.3750  T=0.0311
2026-06-26 23:43:34,667 INFO:   step 140  |  intra_contact_loss=2.3946  inter_contact_loss=3.1547  glob_loss=1.8491  total_loss=5.7538  plm_loss=2.6094  T=0.0188
2026-06-26 23:43:40,504 INFO:   step 145  |  intra_contact_loss=2.3528  inter_contact_loss=3.1623  glob_loss=1.8599  total_loss=5.0045  plm_loss=1.8750  T=0.0117
2026-06-26 23:43:45,173 WARNING: iptm never computed for batch 0; using last-step sequence as fallback
2026-06-26 23:43:51,519 INFO:   step   0  |  intra_contact_loss=4.2807  inter_contact_loss=3.9533  glob_loss=3.4547  total_loss=7.8704  plm_loss=3.0625  T=0.9999
2026-06-26 23:43:54,710 INFO:   step   5  |  intra_contact_loss=3.3461  inter_contact_loss=3.3813  glob_loss=2.3955  total_loss=7.1240  plm_loss=3.2812  T=0.9961
2026-06-26 23:43:58,070 INFO:   step  10  |  intra_contact_loss=3.2674  inter_contact_loss=3.5297  glob_loss=2.1808  total_loss=7.1316  plm_loss=3.2969  T=0.9869
2026-06-26 23:44:01,261 INFO:   step  15  |  intra_contact_loss=3.3920  inter_contact_loss=3.5483  glob_loss=2.1570  total_loss=7.6515  plm_loss=3.7500  T=0.9725
2026-06-26 23:44:04,452 INFO:   step  20  |  intra_contact_loss=3.2218  inter_contact_loss=3.4222  glob_loss=2.0554  total_loss=7.2018  plm_loss=3.4688  T=0.9529
2026-06-26 23:44:07,642 INFO:   step  25  |  intra_contact_loss=3.3070  inter_contact_loss=3.3336  glob_loss=2.0538  total_loss=7.1686  plm_loss=3.4375  T=0.9284
2026-06-26 23:44:10,836 INFO:   step  30  |  intra_contact_loss=3.2820  inter_contact_loss=3.4643  glob_loss=2.0311  total_loss=7.2325  plm_loss=3.4531  T=0.8993
2026-06-26 23:44:14,193 INFO:   step  35  |  intra_contact_loss=3.1720  inter_contact_loss=3.3262  glob_loss=2.0933  total_loss=7.1678  plm_loss=3.5000  T=0.8658
2026-06-26 23:44:17,383 INFO:   step  40  |  intra_contact_loss=3.3877  inter_contact_loss=3.4753  glob_loss=2.0659  total_loss=7.4540  plm_loss=3.6094  T=0.8284
2026-06-26 23:44:20,574 INFO:   step  45  |  intra_contact_loss=3.4208  inter_contact_loss=3.7281  glob_loss=2.0854  total_loss=7.3196  plm_loss=3.3281  T=0.7875
2026-06-26 23:44:23,768 INFO:   step  50  |  intra_contact_loss=3.2331  inter_contact_loss=3.3594  glob_loss=2.0184  total_loss=7.0437  plm_loss=3.3438  T=0.7435
2026-06-26 23:44:27,129 INFO:   step  55  |  intra_contact_loss=3.2536  inter_contact_loss=3.4469  glob_loss=1.9672  total_loss=7.1812  plm_loss=3.4375  T=0.6968
2026-06-26 23:44:30,322 INFO:   step  60  |  intra_contact_loss=3.2074  inter_contact_loss=3.3670  glob_loss=1.9479  total_loss=6.8955  plm_loss=3.2188  T=0.6481
2026-06-26 23:44:33,513 INFO:   step  65  |  intra_contact_loss=3.2583  inter_contact_loss=3.4310  glob_loss=2.0091  total_loss=7.0121  plm_loss=3.2656  T=0.5978
2026-06-26 23:44:36,918 INFO:   step  70  |  intra_contact_loss=3.1173  inter_contact_loss=3.3718  glob_loss=1.9947  total_loss=6.6591  plm_loss=3.0156  T=0.5464
2026-06-26 23:44:40,110 INFO:   step  75  |  intra_contact_loss=3.1222  inter_contact_loss=3.3488  glob_loss=1.9535  total_loss=6.2981  plm_loss=2.6719  T=0.4946
2026-06-26 23:44:43,304 INFO:   step  80  |  intra_contact_loss=3.2021  inter_contact_loss=3.3146  glob_loss=1.9857  total_loss=6.4836  plm_loss=2.8281  T=0.4430
2026-06-26 23:44:46,497 INFO:   step  85  |  intra_contact_loss=3.0073  inter_contact_loss=3.2096  glob_loss=1.8928  total_loss=6.2370  plm_loss=2.7500  T=0.3920
2026-06-26 23:44:49,861 INFO:   step  90  |  intra_contact_loss=3.0198  inter_contact_loss=3.2836  glob_loss=1.8687  total_loss=5.8223  plm_loss=2.2969  T=0.3422
2026-06-26 23:44:53,053 INFO:   step  95  |  intra_contact_loss=2.9646  inter_contact_loss=3.2713  glob_loss=1.8785  total_loss=5.4859  plm_loss=1.9922  T=0.2942
2026-06-26 23:44:56,247 INFO:   step 100  |  intra_contact_loss=3.0059  inter_contact_loss=3.3159  glob_loss=1.8199  total_loss=5.3530  plm_loss=1.8281  T=0.2486
2026-06-26 23:44:59,630 INFO:   step 105  |  intra_contact_loss=2.9472  inter_contact_loss=3.2655  glob_loss=1.8063  total_loss=5.8270  plm_loss=2.3594  T=0.2057
2026-06-26 23:45:02,823 INFO:   step 110  |  intra_contact_loss=3.0540  inter_contact_loss=3.3038  glob_loss=1.8540  total_loss=5.5810  plm_loss=2.0312  T=0.1661
2026-06-26 23:45:06,037 INFO:   step 115  |  intra_contact_loss=3.0341  inter_contact_loss=3.2994  glob_loss=1.8189  total_loss=5.4524  plm_loss=1.9219  T=0.1303
2026-06-26 23:45:09,402 INFO:   step 120  |  intra_contact_loss=2.9975  inter_contact_loss=3.4888  glob_loss=1.7855  total_loss=5.7253  plm_loss=2.1250  T=0.0985
2026-06-26 23:45:12,602 INFO:   step 125  |  intra_contact_loss=3.0091  inter_contact_loss=3.4054  glob_loss=1.8319  total_loss=5.3471  plm_loss=1.7734  T=0.0712
2026-06-26 23:45:16,347 INFO:   step 130  |  intra_contact_loss=3.0151  inter_contact_loss=3.3362  glob_loss=1.8479  total_loss=5.1781  plm_loss=1.6328  T=0.0487
2026-06-26 23:45:22,371 INFO:   step 135  |  intra_contact_loss=3.0339  inter_contact_loss=3.4086  glob_loss=1.7829  total_loss=5.4060  plm_loss=1.8281  T=0.0311
2026-06-26 23:45:28,255 INFO:   step 140  |  intra_contact_loss=3.0348  inter_contact_loss=3.4309  glob_loss=1.8126  total_loss=5.4079  plm_loss=1.8125  T=0.0188
2026-06-26 23:45:34,338 INFO:   step 145  |  intra_contact_loss=3.0937  inter_contact_loss=3.4607  glob_loss=1.8234  total_loss=5.0403  plm_loss=1.3984  T=0.0117
2026-06-26 23:45:39,035 WARNING: iptm never computed for batch 0; using last-step sequence as fallback

Completed 50/50 jobs -> 100 result rows

In [15]:
print(len(failures))
print(failures[:3])

0
[]

## 4. Pick the designs to order

This is your final shortlist. The cell below:

1. Combines results from all successful jobs into one dataframe.
2. Filters minibinders to isoelectric point under 6 (helps with solubility and expression). Antibodies pass through unfiltered.
3. Scores each unique designed sequence by averaging `iptm` (interface predicted TM-score, higher is better) and an `iptm_proxy` term across its trajectories.
4. Returns the top 84 designs per (target, binder type), saved to `selection.parquet` inside your `save_dir`.

84 is a plate-friendly number for ordering and screening. The cutoff and the isoelectric-point filter are currently hardcoded inside the cell, so to change them, edit the values directly in the function.

In [17]:
# ---- Select (instrumented) ----

# Tunables ----------------------------------------------------------
PI_THRESHOLD = None      # set e.g. 8.0 to filter by isoelectric point
TOP_N = 84               # designs to keep per (target, binder) group
SCALING_CHECKPOINT_SUBSTRING = "ESMFold2-Experimental-Fast-base"
# -------------------------------------------------------------------

print(f"[1] rows collected from successful jobs: {len(df_result)}")
print(f"    unique designed_sequence: {df_result.designed_sequence.nunique()}")

if df_result.empty:
    raise ValueError(
        "df_result is empty — no successful job results were collected. "
        "Check the failures list printed by the sweep cell upstream."
    )

df_result["binder_sequence"] = df_result.designed_sequence.str.split(r"\|").str[1]
df_result["isoelectric_point"] = [
    ProteinAnalysis(seq).isoelectric_point()
    for seq in tqdm(df_result.binder_sequence.values)
]
print(
    f"[2] pI distribution: min={df_result.isoelectric_point.min():.2f} "
    f"median={df_result.isoelectric_point.median():.2f} "
    f"max={df_result.isoelectric_point.max():.2f}"
)

if PI_THRESHOLD is None:
    df_filter = df_result.copy()
    print("[3] pI filter DISABLED — keeping all designs")
else:
    df_filter = df_result[
        df_result.is_antibody | df_result.isoelectric_point.lt(PI_THRESHOLD)
    ]
    n_drop = df_result.designed_sequence.nunique() - df_filter.designed_sequence.nunique()
    print(
        f"[3] after pI<{PI_THRESHOLD} filter: {df_filter.designed_sequence.nunique()} "
        f"unique designs kept ({n_drop} dropped)"
    )

if df_filter.empty:
    raise ValueError(
        f"All designs were removed by the pI filter. Raise PI_THRESHOLD or set to None."
    )


def select(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    is_scaling = df.critic_name.str.contains(
        SCALING_CHECKPOINT_SUBSTRING, regex=False, na=False
    )
    iptm_proxy = df.distogram_iptm_proxy.where(
        ~df.is_antibody, df.cdr_distogram_iptm_proxy
    )
    df["iptm_score"] = df.iptm.where(~is_scaling)
    df["iptm_proxy_score"] = iptm_proxy.where(is_scaling)

    contact_cols = [c for c in df.columns if c.startswith("contact_site")]
    has_avoid = "contact_avoid" in df.columns
    agg_spec = dict(
        iptm_score=("iptm_score", "mean"),
        iptm_proxy_score=("iptm_proxy_score", "mean"),
        **{c: (c, "mean") for c in contact_cols},
        **(dict(contact_avoid=("contact_avoid", "mean")) if has_avoid else {}),
    )
    scores = df.groupby("designed_sequence", as_index=False).agg(**agg_spec)

    site_contact = scores[contact_cols].fillna(0).mean(axis=1) if contact_cols else 0.0
    avoid_penalty = scores["contact_avoid"].fillna(0) if has_avoid else 0.0
    scores["selection_score"] = (
        0.5 * scores.iptm_proxy_score.fillna(0)
        + 0.3 * site_contact
        - 0.2 * avoid_penalty
    )
    return scores.nlargest(min(len(scores), TOP_N), "selection_score")


df_select = df_filter.groupby(["target_name", "binder_name"], dropna=False).apply(
    select, include_groups=False
)
df_select.to_parquet(save_dir / "selection.parquet", index=False)
print(f"[4] final selection: {len(df_select)} designs -> {save_dir / 'selection.parquet'}")
df_select

[1] rows collected from successful jobs: 100
    unique designed_sequence: 50

  0%|          | 0/100 [00:00<?, ?it/s]

[2] pI distribution: min=4.05 median=10.30 max=12.00
[3] pI filter DISABLED — keeping all designs
[4] final selection: 50 designs -> sweep/selection.parquet

                                                            designed_sequence  \
target_name binder_name
NaN         NaN         27  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        3   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        2   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        5   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        21  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        45  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        25  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        37  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        39  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        40  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        0   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        49  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        23  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        12  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        9   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        19  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        24  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        22  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        14  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        38  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        35  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        4   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        41  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        6   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        47  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        36  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        11  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        17  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        46  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        28  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        32  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        16  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        48  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        10  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        1   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        20  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        13  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        43  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        29  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        8   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        31  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        15  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        33  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        34  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        26  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        18  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        7   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        30  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        44  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        42  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...

                           iptm_score  iptm_proxy_score  contact_site1_helix  \
target_name binder_name
NaN         NaN         27        NaN          0.475435               0.1875
                        3         NaN          0.393968               0.3125
                        2         NaN          0.437682               0.2500
                        5         NaN          0.479409               0.2500
                        21        NaN          0.413838               0.1875
                        45        NaN          0.458545               0.2500
                        25        NaN          0.417812               0.0625
                        37        NaN          0.437682               0.1875
                        39        NaN          0.425760               0.1250
                        40        NaN          0.393968               0.1250
                        0         NaN          0.395955               0.1875
                        49        NaN          0.415825               0.1875
                        23        NaN          0.393968               0.2500
                        12        NaN          0.384033               0.1875
                        9         NaN          0.366150               0.1250
                        19        NaN          0.399929               0.1250
                        24        NaN          0.366150               0.1875
                        22        NaN          0.437682               0.1875
                        14        NaN          0.384033               0.3125
                        38        NaN          0.372111               0.0625
                        35        NaN          0.362176               0.2500
                        4         NaN          0.380059               0.1875
                        41        NaN          0.374098               0.3125
                        6         NaN          0.332371               0.2500
                        47        NaN          0.342306               0.2500
                        36        NaN          0.310514               0.3750
                        11        NaN          0.358202               0.3125
                        17        NaN          0.340319               0.2500
                        46        NaN          0.284683               0.2500
                        28        NaN          0.394961               0.2500
                        32        NaN          0.316475               0.2500
                        16        NaN          0.336345               0.1875
                        48        NaN          0.310514               0.2500
                        10        NaN          0.308527               0.3125
                        1         NaN          0.358202               0.3125
                        20        NaN          0.358202               0.2500
                        13        NaN          0.354228               0.2500
                        43        NaN          0.314488               0.2500
                        29        NaN          0.340319               0.3125
                        8         NaN          0.344293               0.1875
                        31        NaN          0.286670               0.1875
                        15        NaN          0.312501               0.1875
                        33        NaN          0.322436               0.1875
                        34        NaN          0.344293               0.2500
                        26        NaN          0.284683               0.2500
                        18        NaN          0.318462               0.0625
                        7         NaN          0.302566               0.2500
                        30        NaN          0.324423               0.3125
                        44        NaN          0.266801               0.1250
                        42        NaN          0.280709               0.2500

                            contact_site2_loop  contact_site3_hydrophobic  \
target_name binder_name
NaN         NaN         27            0.333333                   0.666667
                        3             0.458333                   0.666667
                        2             0.416667                   0.555556
                        5             0.333333                   0.555556
                        21            0.333333                   0.722222
                        45            0.250000                   0.555556
                        25            0.458333                   0.777778
                        37            0.333333                   0.611111
                        39            0.333333                   0.722222
                        40            0.375000                   0.722222
                        0             0.333333                   0.777778
                        49            0.291667                   0.611111
                        23            0.291667                   0.555556
                        12            0.291667                   0.611111
                        9             0.416667                   0.555556
                        19            0.458333                   0.555556
                        24            0.333333                   0.611111
                        22            0.291667                   0.722222
                        14            0.291667                   0.555556
                        38            0.333333                   0.722222
                        35            0.291667                   0.722222
                        4             0.250000                   0.500000
                        41            0.250000                   0.444444
                        6             0.416667                   0.666667
                        47            0.375000                   0.500000
                        36            0.333333                   0.555556
                        11            0.166667                   0.666667
                        17            0.333333                   0.555556
                        46            0.333333                   0.833333
                        28            0.291667                   0.444444
                        32            0.375000                   0.611111
                        16            0.333333                   0.611111
                        48            0.416667                   0.500000
                        10            0.291667                   0.500000
                        1             0.250000                   0.500000
                        20            0.291667                   0.500000
                        13            0.333333                   0.555556
                        43            0.291667                   0.611111
                        29            0.166667                   0.500000
                        8             0.375000                   0.666667
                        31            0.291667                   0.666667
                        15            0.291667                   0.666667
                        33            0.291667                   0.555556
                        34            0.166667                   0.444444
                        26            0.250000                   0.500000
                        18            0.291667                   0.722222
                        7             0.250000                   0.611111
                        30            0.125000                   0.333333
                        44            0.333333                   0.333333
                        42            0.125000                   0.500000

                            contact_avoid  selection_score
target_name binder_name
NaN         NaN         27       0.000000         0.356467
                        3        0.000000         0.340734
                        2        0.021739         0.336715
                        5        0.108696         0.331854
                        21       0.000000         0.331224
                        45       0.021739         0.330480
                        25       0.065217         0.325724
                        37       0.043478         0.323340
                        39       0.086957         0.313544
                        40       0.043478         0.310511
                        0        0.086957         0.310447
                        49       0.043478         0.308245
                        23       0.043478         0.298011
                        12       0.021739         0.296696
                        9        0.000000         0.292797
                        19       0.108696         0.292114
                        24       0.021739         0.291922
                        22       0.239130         0.291154
                        14       0.086957         0.290597
                        38       0.043478         0.289165
                        35       0.108696         0.285738
                        4        0.000000         0.283779
                        41       0.021739         0.283396
                        6        0.086957         0.282128
                        47       0.021739         0.279305
                        36       0.043478         0.272950
                        11       0.108696         0.271945
                        17       0.065217         0.271005
                        46       0.065217         0.270965
                        28       0.130435         0.270005
                        32       0.065217         0.268805
                        16       0.065217         0.268324
                        48       0.021739         0.267576
                        10       0.000000         0.264680
                        1        0.108696         0.263612
                        20       0.108696         0.261529
                        13       0.152174         0.260568
                        43       0.065217         0.259478
                        29       0.043478         0.259381
                        8        0.217391         0.251585
                        31       0.065217         0.244875
                        15       0.130435         0.244747
                        33       0.108696         0.242951
                        34       0.086957         0.240866
                        26       0.043478         0.233646
                        18       0.195652         0.227740
                        7        0.217391         0.218916
                        30       0.108696         0.217556
                        44       0.043478         0.203871
                        42       0.152174         0.197420

In [18]:
df_result[df_result.critic_name.eq("ESMFold2-Experimental-Fast-base300M-step1500k")].drop(
    columns=["complex", "logits"]
)

,is_antibody,critic_name,batch_idx,designed_sequence,final_loss,iptm,distogram_iptm_proxy,cdr_distogram_iptm_proxy,target_name,target_sequence,binder_name,binder_sequence,use_scaling_critics,seed,batch_size,contact_site1_helix,contact_site2_loop,contact_site3_hydrophobic,contact_avoid,isoelectric_point
1,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.133523,None,0.427747,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,KKKLLKVAAVIILVVALLVGALLSSGGGGLAKKVIKLALKLVKKVL...,False,0,1,0.375,0.416667,0.555556,0.000000,11.000128
3,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.101623,None,0.288657,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,VKLTRQQLLQLAVAAIVAAAAAAAAAGNSKLVLLLLLLGLLLVLLL...,False,1,1,0.375,0.166667,0.555556,0.217391,11.166198
5,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.746590,None,0.479409,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,SSLLKMLLLLLLLLLVLKYLYQNGLLSPSQYQRYKSFLLGMLKMLL...,False,2,1,0.250,0.333333,0.666667,0.043478,10.214516
7,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.610528,None,0.352241,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,LLLLLLLVLVTAVHTALTALTLLGNGGGLLLALLLLLLLLALAVVL...,False,3,1,0.375,0.250000,0.666667,0.000000,6.741127
9,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.616396,None,0.513187,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,VNAYQIARLVLTAALLGLLLLVLPDKGGSLAEKLLRLLVSVLAELY...,False,4,1,0.250,0.250000,0.555556,0.043478,9.818293
11,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.472350,None,0.376085,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,LLGLLLRVLRKATTVASSLASSSSPSSSTLLLALLLLLVALLALLL...,False,5,1,0.250,0.416667,0.666667,0.173913,10.835024
13,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.510911,None,0.272761,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,MNLLLLLLNVILNIANLLLSLYKSGKLSKEQVLVILLLLLLLLLLL...,False,6,1,0.375,0.250000,0.444444,0.086957,9.824482
15,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.492664,None,0.324423,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,LLLLLLLLLLLVLLLSKLVKKLSSSGKNPGAVLALLKTAISMLALL...,False,7,1,0.250,0.250000,0.666667,0.391304,10.602487
17,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.423659,None,0.304553,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,MIWLVLVAAAAAAAAASGNPGLAVAVVTAAAYLAANGGGLAALIVA...,False,8,1,0.000,0.333333,0.888889,0.304348,5.274795
19,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.476138,None,0.554914,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,GLTPRQVALLVFLTALLALAVSSSGGSSGSGKLAKAVGTAVTYAVT...,False,9,1,0.250,0.500000,0.444444,0.000000,10.289686
21,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.307140,None,0.451591,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,MLTAQLVKLLLRTALTALIVLALGGSGKAAKLAAKALKKQVKALAR...,False,10,1,0.250,0.333333,0.666667,0.086957,11.999968
23,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.400484,None,0.304553,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,NLLDLLLLLLLLLLLLVPKLSKTNPSLAKKLLPLAVKLAQLLLLLF...,False,11,1,0.375,0.416667,0.555556,0.086957,10.176866
25,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.286667,None,0.463513,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,LNLSLVLKLGKAASTLLPRAISLLKQGNVKQAAIVLLIVALLLKLL...,False,12,1,0.125,0.333333,0.666667,0.000000,11.388421
27,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.151961,None,0.407877,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,LLLLLLLTALLLLLLAAALVASGSSPSTLALARKLVRAAVTYVRLA...,False,13,1,0.125,0.416667,0.666667,0.000000,11.723012
29,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.647361,None,0.431721,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,GLLLLLVTAVVYSVLLLLYLASSGNTELVKTAALLTLLLAIVAAAV...,False,14,1,0.250,0.250000,0.444444,0.043478,8.430934
31,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.760699,None,0.344293,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,VSLVALLTGFVVLAASYLAGSGGSPETTALVVLLVALVSGGGAVLW...,False,15,1,0.250,0.416667,0.444444,0.043478,4.050028
33,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.427002,None,0.523122,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,MNLLNKLLKALMRALNEVKNTLKNGGGGATLTRLLVIVFLLLLLLV...,False,16,1,0.250,0.333333,0.666667,0.000000,11.165940
35,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,6.078942,None,0.479409,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,MKKLLLIVVSVLYSSLSALNAANNSGSTAALKKVVITTLIAALVVV...,False,17,1,0.250,0.333333,0.444444,0.086957,10.176351
37,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.294384,None,0.336345,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,NLLLLLLLLAQKLLQLLKPALKSGSASAKKLLALAIALLLLLLLVL...,False,18,1,0.375,0.250000,0.555556,0.086957,10.602487
39,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.933633,None,0.391981,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,NNLLLLLLLLTLLVAHVLQKYASSTGKHQKVRKLTNKLLKMVKVLL...,False,19,1,0.250,0.250000,0.666667,0.217391,10.870546
41,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.257296,None,0.471461,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,MKLLLRLLLMILVMSFVIKALKKNGSNNGKLQMAKRMLKMPLRMLK...,False,20,1,0.250,0.333333,0.666667,0.347826,11.999968
43,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.469436,None,0.523122,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,MKLLKLLKSLLRVALSLASALSSSGGSGDAALTVVAAVILLALLVA...,False,21,1,0.125,0.416667,0.777778,0.000000,10.288977
45,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.509747,None,0.344293,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,NLAQQLIQAIITVAKIAIPALKKSGNNKLLKKVLILLLLLLLLLLK...,False,22,1,0.500,0.250000,0.555556,0.130435,10.778421
47,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,4.739554,None,0.431721,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,LSFLQYLHLLLEEAGLGELFEAAVAAAASGGAAGLLLLVLLVLLVL...,False,23,1,0.250,0.333333,0.555556,0.086957,4.087997
49,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.480185,None,0.471461,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,SQLLLLLVVQEVPLQLKQLSLLSSQLSPQQYKRQAVKVLLQALILF...,False,24,1,0.125,0.333333,0.777778,0.086957,9.996097
51,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.863871,None,0.304553,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,NSLLKLLQNLRLAAKKLAKYLLKSGNTKLALLVLLLVEILVRLLLK...,False,25,1,0.500,0.333333,0.666667,0.043478,10.582566
53,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.596663,None,0.388007,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,MILVAVVAALIVAAILVKVAKKNGGNPELMKAVAAVVAVLVAAVAA...,False,26,1,0.250,0.250000,0.555556,0.086957,10.176351
55,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.170341,None,0.411851,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,SLLLLLLKLARKLVQSGNLALAVLVALLAVLLLGGNPQLAVAVVAA...,False,27,1,0.000,0.333333,0.777778,0.000000,11.166005
57,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,4.761081,None,0.332371,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,LSLLQLLLLALSGGGGGGLAAAVAAAAVAALNGGGALAVVAALLLL...,False,28,1,0.250,0.333333,0.777778,0.043478,5.525000
59,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.518183,None,0.497291,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,MNLNKKLLKRLLLALLLMTIVVAKVAKLTGNPQLLQLAKNLLKLLV...,False,29,1,0.250,0.333333,0.333333,0.217391,11.505173
61,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.633863,None,0.483382,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,LLARLQRLRSYALSRLKSALKGGESDEELVFLILLTLFTDIILRYL...,False,30,1,0.250,0.333333,0.555556,0.130435,9.518838
63,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,4.889747,None,0.495304,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,MNKLKLLKLAFSLLKEAFNLAKNSGSSASVLRQVAIIILAAALLLL...,False,31,1,0.125,0.416667,0.666667,0.043478,10.582501
65,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.693575,None,0.372111,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,MGLILAVLKATAKIASAALSYLSSNGGADLAALVIIVLLAVAIVVL...,False,32,1,0.250,0.333333,0.666667,0.086957,8.253839
67,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.624821,None,0.467487,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,LKLLLLLLLGVAAVSVLSWALRVGAGNPQLLKAAATLVLILLLLAL...,False,33,1,0.250,0.250000,0.444444,0.000000,11.166263
69,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.287692,None,0.419799,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,MKLKLLLLLMKIVKKAMKMAKKLAKSGNTTQALVLLILVALLVLLV...,False,34,1,0.500,0.333333,0.555556,0.173913,10.954291
71,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.333289,None,0.451591,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,SLKRLLLQVLLTALLVKVLLNEASSSSNSSRLRRLARRARRRLRQL...,False,35,1,0.125,0.333333,0.555556,0.043478,11.999968
73,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.796922,None,0.316475,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,VLLGAVVLVVAFWSVIASYVLSTLGGPGAVAAATAVVTATVAAVVV...,False,36,1,0.250,0.333333,0.666667,0.086957,5.494364
75,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.391542,None,0.411851,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,MNKLKLLKKAVNRLNNALNQLQTNGSNSPGLLKQLAKAALEALILV...,False,37,1,0.125,0.333333,0.666667,0.043478,10.675916
77,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.325997,None,0.423773,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,VKLLGLLVAVLVALALSLVSRAASSGGSGGALLVATALLSQLLAAL...,False,38,1,0.375,0.250000,0.444444,0.000000,11.000708
79,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.843610,None,0.407877,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,LSKPQLLQVLEALQSVAQPVAQYLIKSGNTLLALVLLILVKLLTVL...,False,39,1,0.375,0.333333,0.555556,0.130435,9.997128
81,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.260959,None,0.304553,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,VQQLLQLILQAVQLLARYIATNAPNPKLAKKLLILLLLLVLLLLRL...,False,40,1,0.375,0.333333,0.888889,0.086957,11.219707
83,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.502491,None,0.483382,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,GKLLKLVAAALTGAGTLVSSLLSSGGGEQAIKAVAIAILLVPLVVV...,False,41,1,0.125,0.333333,0.666667,0.043478,9.703024
85,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.328097,None,0.272761,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,VLSLLLLLLLLILLLGLVLLHLLKSGGNSKLLLVVLLLLLLLLSLL...,False,42,1,0.000,0.416667,0.333333,0.043478,10.002479
87,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.711325,None,0.403903,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,MSRSQLKLLALLVLLLVLLVAKPVAKNGGSPALLAAVVSVAAVVVV...,False,43,1,0.375,0.166667,0.555556,0.043478,11.263674
89,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.428519,None,0.411851,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,LLQLLLLLPLQAATLLPQALLSAGFSLSPKTVLVLLILALLLALVL...,False,44,1,0.375,0.166667,0.777778,0.043478,10.002737
91,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,4.969149,None,0.407877,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,NNIQAILQLIQVIQHLAQHVKQHSGNSKLLKLLLLLLKLLLLLLLL...,False,45,1,0.250,0.083333,0.444444,0.086957,10.602551
93,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.138161,None,0.391981,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,LLLLLLLLLVLLLAKLAKQNPSLQPVARAMATVASSLLGGGDLLLL...,False,46,1,0.375,0.416667,0.666667,0.304348,9.994292
95,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.853415,None,0.324423,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,NLLLLLLKLVTTVIKKAFYLYKNGKLSPKQFVLVLLLALLLVLVVL...,False,47,1,0.250,0.500000,0.666667,0.000000,10.301355
97,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,6.165007,None,0.463513,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,VVTLVVALVAYAYSTLSTLANSGSGLTPQQLARQVVRAFLAALLAV...,False,48,1,0.250,0.250000,0.555556,0.000000,9.985782
99,False,ESMFold2-Experimental-Fast-base300M-step1500k,0,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,5.414867,None,0.419799,NaN,None,SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...,None,VRLGLGELLQVLLKLATSLLKLALSNGGLTPLAAALLVLLLLVAVV...,False,49,1,0.125,0.416667,0.555556,0.000000,9.993970

In [19]:
df_select

                                                            designed_sequence  \
target_name binder_name
NaN         NaN         27  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        3   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        2   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        5   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        21  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        45  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        25  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        37  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        39  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        40  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        0   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        49  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        23  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        12  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        9   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        19  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        24  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        22  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        14  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        38  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        35  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        4   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        41  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        6   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        47  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        36  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        11  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        17  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        46  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        28  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        32  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        16  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        48  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        10  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        1   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        20  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        13  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        43  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        29  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        8   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        31  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        15  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        33  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        34  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        26  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        18  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        7   SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        30  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        44  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...
                        42  SELEKAMVALIDVFHQYSGREGDKHKLKKSELKELINNELSHFLEE...

                           iptm_score  iptm_proxy_score  contact_site1_helix  \
target_name binder_name
NaN         NaN         27        NaN          0.475435               0.1875
                        3         NaN          0.393968               0.3125
                        2         NaN          0.437682               0.2500
                        5         NaN          0.479409               0.2500
                        21        NaN          0.413838               0.1875
                        45        NaN          0.458545               0.2500
                        25        NaN          0.417812               0.0625
                        37        NaN          0.437682               0.1875
                        39        NaN          0.425760               0.1250
                        40        NaN          0.393968               0.1250
                        0         NaN          0.395955               0.1875
                        49        NaN          0.415825               0.1875
                        23        NaN          0.393968               0.2500
                        12        NaN          0.384033               0.1875
                        9         NaN          0.366150               0.1250
                        19        NaN          0.399929               0.1250
                        24        NaN          0.366150               0.1875
                        22        NaN          0.437682               0.1875
                        14        NaN          0.384033               0.3125
                        38        NaN          0.372111               0.0625
                        35        NaN          0.362176               0.2500
                        4         NaN          0.380059               0.1875
                        41        NaN          0.374098               0.3125
                        6         NaN          0.332371               0.2500
                        47        NaN          0.342306               0.2500
                        36        NaN          0.310514               0.3750
                        11        NaN          0.358202               0.3125
                        17        NaN          0.340319               0.2500
                        46        NaN          0.284683               0.2500
                        28        NaN          0.394961               0.2500
                        32        NaN          0.316475               0.2500
                        16        NaN          0.336345               0.1875
                        48        NaN          0.310514               0.2500
                        10        NaN          0.308527               0.3125
                        1         NaN          0.358202               0.3125
                        20        NaN          0.358202               0.2500
                        13        NaN          0.354228               0.2500
                        43        NaN          0.314488               0.2500
                        29        NaN          0.340319               0.3125
                        8         NaN          0.344293               0.1875
                        31        NaN          0.286670               0.1875
                        15        NaN          0.312501               0.1875
                        33        NaN          0.322436               0.1875
                        34        NaN          0.344293               0.2500
                        26        NaN          0.284683               0.2500
                        18        NaN          0.318462               0.0625
                        7         NaN          0.302566               0.2500
                        30        NaN          0.324423               0.3125
                        44        NaN          0.266801               0.1250
                        42        NaN          0.280709               0.2500

                            contact_site2_loop  contact_site3_hydrophobic  \
target_name binder_name
NaN         NaN         27            0.333333                   0.666667
                        3             0.458333                   0.666667
                        2             0.416667                   0.555556
                        5             0.333333                   0.555556
                        21            0.333333                   0.722222
                        45            0.250000                   0.555556
                        25            0.458333                   0.777778
                        37            0.333333                   0.611111
                        39            0.333333                   0.722222
                        40            0.375000                   0.722222
                        0             0.333333                   0.777778
                        49            0.291667                   0.611111
                        23            0.291667                   0.555556
                        12            0.291667                   0.611111
                        9             0.416667                   0.555556
                        19            0.458333                   0.555556
                        24            0.333333                   0.611111
                        22            0.291667                   0.722222
                        14            0.291667                   0.555556
                        38            0.333333                   0.722222
                        35            0.291667                   0.722222
                        4             0.250000                   0.500000
                        41            0.250000                   0.444444
                        6             0.416667                   0.666667
                        47            0.375000                   0.500000
                        36            0.333333                   0.555556
                        11            0.166667                   0.666667
                        17            0.333333                   0.555556
                        46            0.333333                   0.833333
                        28            0.291667                   0.444444
                        32            0.375000                   0.611111
                        16            0.333333                   0.611111
                        48            0.416667                   0.500000
                        10            0.291667                   0.500000
                        1             0.250000                   0.500000
                        20            0.291667                   0.500000
                        13            0.333333                   0.555556
                        43            0.291667                   0.611111
                        29            0.166667                   0.500000
                        8             0.375000                   0.666667
                        31            0.291667                   0.666667
                        15            0.291667                   0.666667
                        33            0.291667                   0.555556
                        34            0.166667                   0.444444
                        26            0.250000                   0.500000
                        18            0.291667                   0.722222
                        7             0.250000                   0.611111
                        30            0.125000                   0.333333
                        44            0.333333                   0.333333
                        42            0.125000                   0.500000

                            contact_avoid  selection_score
target_name binder_name
NaN         NaN         27       0.000000         0.356467
                        3        0.000000         0.340734
                        2        0.021739         0.336715
                        5        0.108696         0.331854
                        21       0.000000         0.331224
                        45       0.021739         0.330480
                        25       0.065217         0.325724
                        37       0.043478         0.323340
                        39       0.086957         0.313544
                        40       0.043478         0.310511
                        0        0.086957         0.310447
                        49       0.043478         0.308245
                        23       0.043478         0.298011
                        12       0.021739         0.296696
                        9        0.000000         0.292797
                        19       0.108696         0.292114
                        24       0.021739         0.291922
                        22       0.239130         0.291154
                        14       0.086957         0.290597
                        38       0.043478         0.289165
                        35       0.108696         0.285738
                        4        0.000000         0.283779
                        41       0.021739         0.283396
                        6        0.086957         0.282128
                        47       0.021739         0.279305
                        36       0.043478         0.272950
                        11       0.108696         0.271945
                        17       0.065217         0.271005
                        46       0.065217         0.270965
                        28       0.130435         0.270005
                        32       0.065217         0.268805
                        16       0.065217         0.268324
                        48       0.021739         0.267576
                        10       0.000000         0.264680
                        1        0.108696         0.263612
                        20       0.108696         0.261529
                        13       0.152174         0.260568
                        43       0.065217         0.259478
                        29       0.043478         0.259381
                        8        0.217391         0.251585
                        31       0.065217         0.244875
                        15       0.130435         0.244747
                        33       0.108696         0.242951
                        34       0.086957         0.240866
                        26       0.043478         0.233646
                        18       0.195652         0.227740
                        7        0.217391         0.218916
                        30       0.108696         0.217556
                        44       0.043478         0.203871
                        42       0.152174         0.197420